# Generated by Django 2.2.3 on 2019-07-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('authors', models.CharField(max_length=250)),
                ('publishedDate', models.DateField(blank=True, null=True)),
                ('industryIdentifiers', models.TextField(max_length=300)),
                ('pageCount', models.IntegerField(blank=True, null=True)),
                ('imageLinks', models.URLField(blank=True, null=True)),
                ('language', models.CharField(max_length=5)),
            ],
        ),
    ]
