# Generated by Django 2.2.3 on 2019-07-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_bk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='industryIdentifiers',
            field=models.TextField(blank=True),
        ),
    ]
