# Generated by Django 2.2.3 on 2019-07-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_bk', '0002_auto_20190729_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='industryIdentifiers',
        ),
        migrations.AddField(
            model_name='books',
            name='isbn10',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='isbn13',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
