# Generated by Django 2.2.3 on 2019-07-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_bk', '0003_auto_20190730_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn10',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn13',
            field=models.CharField(max_length=25),
        ),
    ]
